#name = input("Enter yourr name:")
#age = int(input("Enter your age:"))
#college = input("Enter your college:")
#print("Name:",name)
#print("Age:",age)
#print("College:",college)
#Day1 part2
a = int(input("Enter the first number:"))
b = int(input("Enter the second number:"))
print("Addition:",a + b)
print("Substraction:",a - b)
print("Multification:",a * b)
print("Division:",a / b)
print("Floor Division:",a // b)
print("Remainder:",a % b)